version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      VIRTUAL_HOST: yeatwork.ru
      LETSENCRYPT_HOST: yeatwork.ru
      LETSENCRYPT_EMAIL: ruslan.kuyanets@yandex.ru
    ports:
      - "8081:5173"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - .env.production
    networks:
      - proxy-net

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - letsencrypt-certs:/etc/nginx/certs
      - letsencrypt-vhost-d:/etc/nginx/vhost.d
      - letsencrypt-html:/usr/share/nginx/html
      - ./nginx/custom_body_size.conf:/etc/nginx/conf.d/custom_body_size.conf
    networks:
      - proxy-net

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt-certs:/etc/nginx/certs
      - letsencrypt-vhost-d:/etc/nginx/vhost.d
      - letsencrypt-html:/usr/share/nginx/html
    volumes_from:
      - nginx-proxy
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    depends_on:
      - nginx-proxy
    networks:
      - proxy-net

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    environment:
      - VIRTUAL_HOST=portainer.yeatwork.ru
      - LETSENCRYPT_HOST=portainer.yeatwork.ru
      - LETSENCRYPT_EMAIL=ruslan.kuyanets@yandex.ru
      - VIRTUAL_PORT=9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - proxy-net
    depends_on:
      - nginx-proxy
      - letsencrypt-companion

volumes:
  letsencrypt-certs:
  letsencrypt-vhost-d:
  letsencrypt-html:
  portainer_data:
    driver: local

networks:
  proxy-net:
    external: true
