name: Deploy Platform

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS for test
        if: github.ref == 'refs/heads/develop'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST_TEST }}
          username: ${{ secrets.VPS_USERNAME_TEST }}
          key: ${{ secrets.VPS_SSH_KEY_TEST }}
          script: |
            cd example
            git checkout develop
            git pull origin develop
            docker-compose --env-file ./frontend/.env.production -f docker-compose.yml up -d --build

      - name: Deploy to VPS for production
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST_PRODUCTION }}
          username: ${{ secrets.VPS_USERNAME_PRODUCTION }}
          key: ${{ secrets.VPS_SSH_KEY_PRODUCTION }}
          script: |
            cd example
            git checkout main
            git pull origin main
            docker-compose --env-file ./frontend/.env.production -f docker-compose.yml up -d --build
